name             'course_jenkins_v3'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures course_jenkins_level_1'
long_description 'Installs/Configures course_jenkins_level_1'
version          '0.3.0'

depends 'apt', '2.6.1'
depends 'jenkins', '2.2.2'
depends 'rvm', '0.9.2'
depends 'chef-sugar', '1.3.0'
depends 'jenkins-chef-dsl'
